name: Publishes and pushes to docker hub
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish on npm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies and build 🔧
      run: npm ci
    - name: Publish package on NPM 📦
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  push_to_registry:
    name: Build and push Docker image to Docker Hub
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Test environment variable
        run: echo ${{ env.RELEASE_VERSION }}
      - name: Check out GitHub repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ./docker/backend
          push: true
          # tags: ${{ github.repository }}:${{ env.RELEASE_VERSION }}
          tags: ${{ github.repository }}:latest
